name: Compile Sing-box Rule-set

on:
  push:
    paths:
      - 'exclude-ru.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sing-box (Direct Download)
        run: |
          # Находим ссылку на последнюю версию для Linux (Ubuntu)
          LATEST_URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep "browser_download_url.*linux-amd64.tar.gz" | cut -d '"' -f 4)
          
          # Скачиваем и распаковываем
          wget -qO sing-box.tar.gz $LATEST_URL
          tar -xzf sing-box.tar.gz
          
          # Перемещаем бинарный файл в системную папку, чтобы команда стала доступна
          sudo cp sing-box-*/sing-box /usr/local/bin/
          
          # Проверяем успешность установки
          sing-box version

      - name: Compile rule-set
        run: |
          sing-box rule-set compile --output exclude-ru.srs exclude-ru.json

      - name: Commit and Push binary
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add exclude-ru.srs
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-compile to SRS" && git push)
