name: Compile Sing-box Rule-set

# Триггеры: когда запускать автоматизацию
on:
  push:
    paths:
      - 'exclude-ru.json' # Запуск только если изменился этот файл
  workflow_dispatch: # Позволяет запускать процесс вручную из интерфейса GitHub

# Разрешения для бота на отправку файлов обратно в репозиторий
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest # Виртуальная машина, на которой все будет происходить
    
    steps:
      # 1. Скачивание вашего репозитория на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка актуальной версии sing-box
      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/web-install.sh)

      # 3. Компиляция JSON в SRS
      - name: Compile rule-set
        run: |
          sing-box rule-set compile --output exclude-ru.srs exclude-ru.json

      # 4. Сохранение и отправка нового бинарного файла в репозиторий
      - name: Commit and Push binary
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add exclude-ru.srs
          
          # Проверяем, есть ли изменения. Если есть - делаем коммит
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-compile to SRS" && git push)
