name: Sync External Rules

on:
  schedule:
    - cron: '0 3 * * *'  # Запускать каждый день в 03:00 (по UTC)
  workflow_dispatch:     # Кнопка для ручного запуска в интерфейсе Actions

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rule sets
        run: |
          # Теперь здесь просто удобный список файлов
          FILES=(
            "geosite-category-ru.srs"
            "geosite-apple.srs"
            "geoip-ru.srs"
            "geosite-google.srs"
            "geosite-google-deepmind.srs"
            "geosite-youtube.srs"
            "geosite-category-ntp.srs"
            "geosite-vokino.srs"
          )

          for file in "${FILES[@]}"; do
            # Магия Bash: отрезаем от имени файла всё, начиная с первого дефиса.
            # Получаем либо "geosite", либо "geoip"
            TYPE="${file%%-*}"
            
            # Подставляем полученный тип в базовый URL
            URL="https://raw.githubusercontent.com/SagerNet/sing-${TYPE}/rule-set/${file}"
            
            echo "Downloading $file from sing-${TYPE}..."
            curl -L -s -o "$file" "$URL"
          done

      - name: Commit and Push binaries
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-sync rule sets"
          file_pattern: "*.srs"
